from typing import List, Dict, Any

def get_unique_sources(retrieved_chunks: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Identifies unique sources based on (document, page) key, preserving
    the retrieval order (relative ranking). Assigns simple sequential numbers.
    
    Args:
        retrieved_chunks: List of chunk dictionaries containing document, page metadata.
        
    Returns:
        A list of deduplicated source dictionaries:
        [
            {"citation_id": 1, "document": "Annual_Report.pdf", "page": 1},
            {"citation_id": 2, "document": "Product_Documentation.pdf", "page": 1}
        ]
    """
    unique_sources = []
    seen = set()
    
    for chunk in retrieved_chunks:
        doc = chunk.get("document")
        page = chunk.get("page")
        
        # Safe fallback if fields are missing
        if doc is None or page is None:
            continue
            
        key = (doc, page)
        if key not in seen:
            seen.add(key)
            unique_sources.append({
                "citation_id": len(unique_sources) + 1,
                "document": doc,
                "page": page
            })
            
    return unique_sources

def format_sources(unique_sources: List[Dict[str, Any]]) -> str:
    """
    Formats the list of unique sources into a readable bibliography block.
    
    Args:
        unique_sources: The deduplicated list from get_unique_sources().
        
    Returns:
        A formatted multi-line string listing the sources.
    """
    if not unique_sources:
        return "No supporting sources were retrieved."
        
    lines = ["Sources:"]
    for src in unique_sources:
        lines.append(f"[{src['citation_id']}] {src['document']} — Page {src['page']}")
        
    return "\n".join(lines)

def append_citations(answer: str, unique_sources: List[Dict[str, Any]]) -> str:
    """
    Combines the LLM-generated answer with citation brackets and the formatted source bibliography.
    
    Args:
        answer: The natural-language answer text generated by the LLM.
        unique_sources: The list of unique sources.
        
    Returns:
        The complete response containing the answer, appended citation tags, and source bibliography.
    """
    answer_clean = answer.strip()
    
    if not unique_sources:
        return f"{answer_clean}\n\nNo supporting sources were retrieved."
        
    # Append sequential citation tags to the end of the text: [1] [2] [3]
    citation_tags = " ".join(f"[{src['citation_id']}]" for src in unique_sources)
    sources_block = format_sources(unique_sources)
    
    return f"{answer_clean} {citation_tags}\n\n{sources_block}"
